version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
  build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR/my-source/golang-app
      - ls -l $CODEBUILD_SRC_DIR/my-source/nodejs-app
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR/my-source/golang-app
      - go build hello.go 
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/my-source/nodejs-app
      - npm run test
  post_build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR/my-source/golang-app
      - ls -l $CODEBUILD_SRC_DIR/my-source/nodejs-app
artifacts:
  files:
    - '*/hello'   
  base-directory: my-source/golang-app
